setup:
  duration: 20
  conn_latency: 1000
  latency: 100
  bandwidth: 1000
init:
  nodes_amount: 10
  edges:
    "1 2": {} 
    "2 3": {} 
    "3 4": {} 
    "4 5": {} 
    "5 6": {} 
    "6 7": {} 
    "7 8": {} 
    "8 9": {} 
    "9 10": {} 
    "10 1": {} 
      