setup:
  duration: 20
  conn_latency: 1000
  latency: 100
  bandwidth: 1000
init:
  nodes_amount: 10
  edges:
    1: [2, 3, 4, 5, 6, 7, 8, 9, 10]
    2: [3, 4, 5, 6, 7, 8, 9, 10]
    3: [4, 5, 6, 7, 8, 9, 10]
    4: [5, 6, 7, 8, 9, 10]
    5: [6, 7, 8, 9, 10]
    6: [7, 8, 9, 10]
    7: [8, 9, 10]
    8: [9, 10]
    9: [10]