setup:
  duration: 10
  conn_latency: 1000
  latency: 20
  bandwidth: 1000
init:
  nodes_amount: 3
  custom_shapes:
    "1 2": {
      conn_lat: 200
    }
  edges:
    1: [2]
    2: [3]
mods:
  - time: 3000
    add: [
      "1 3"
    ]
  - time: 4000
    erase: [
      "1 2"
    ]


    