setup:
  duration: 10
  conn_latency: [1200, 100]
  latency: [20, 10]
  bandwidth: 1000
init:
  nodes_amount: 5
  edges:
    "1 2": {} 
    "2 3": {} 
    "1 3": {} 
    "3 4": {} 
    "3 5": {} 
    "4 5": {} 
mods: 
  - time: 5000
    add: 
      "1 4": {}
      "2 5": {}
    erase: [
      "1 3",
      "3 4"
    ]
      